name: "Run all actions tests"

on:
  push:
    branches:
      - main

jobs:
  test-framework-compose-filename-actions:
    uses: ./.github/workflows/test-framework-compose-filename-shared.yml
    secrets: inherit
